use std::io::Write;

use image::{
    ImageBuffer,
    Rgb,
};

use crate::{
    interval::Interval,
    types::Vec2,
};

// ┌─────────────────────────────────────────────────────────────────────────────┐
// │                                 Path Trait                                  │
// └─────────────────────────────────────────────────────────────────────────────┘
pub(crate) trait Path {
    fn get_intervals(&self, image: &ImageBuffer<Rgb<u8>, Vec<u8>>, angle: f64) -> Vec<Interval>;

    // TODO: Padding for sine sorting?
    fn get_edge_pixels(&self, image_width: u32, image_height: u32, direction: Option<&Vec2>) -> Vec<[u32; 2]> {
        let mut starts: Vec<[u32; 2]> = Vec::new();

        for x in 0..image_width {
            for y in 0..image_height {
                // If the pixel is on the border
                if x == 0 || x == image_width - 1 || y == 0 || y == image_height - 1 {
                    if let Some(dir) = direction {

                        // If a direction is supplied get only the relevant border pixels.
                        let (prev_x, prev_y) = (x as f64 - dir.x, y as f64 - dir.y);
                        if prev_x < 0.0 || prev_x > (image_width - 1) as f64 || prev_y < 0.0 || prev_y > (image_height - 1) as f64 {
                            starts.push([x, y]);
                        }

                    } else {
                        // Otherwise get all border pixels.
                        starts.push([x, y]);
                    }
                }
            }
        }

        starts
    }


    fn print_progress(&self, value: usize, max: Option<usize>) {
        let mut text = format!("Intervals Generated . . . . {}", value);

        if let Some(m) = max {
            text = format!("{} / {}", text, m);
            if value == m { text = format!("{} . . . . . . . . DONE\n", text); }
        }

        print!("\r{}", text);
        std::io::stdout().flush().expect("Could not flush stdout!");
    }

}


// ┌─────────────────────────────────────────────────────────────────────────────┐
// │                                 Linear Path                                 │
// └─────────────────────────────────────────────────────────────────────────────┘
pub(crate) struct LinearPath;

impl LinearPath {
    pub(crate) fn new() -> Self { Self }
}

impl Path for LinearPath {
    // ┌                                                                             ┐
    // │ Intervals are generated by moving from the start position in the direction  │
    // │ of angle until the current pixel is out of bounds.                          │
    // └                                                                             ┘
    fn get_intervals(&self, image: &ImageBuffer<Rgb<u8>, Vec<u8>>, angle: f64) -> Vec<Interval> {
        let mut intervals: Vec<Interval> = Vec::new();
        let direction = Vec2::new_from_angle(angle);
        let start_pixels = self.get_edge_pixels(image.width(), image.height(), Some(&direction));

        for start_px in &start_pixels {
            let mut intvl = Interval::new_empty();
            let mut px = Vec2::new(start_px[0] as f64, start_px[1] as f64);

            while px == px.clamped(Vec2::ZERO, Vec2::new(image.width() as f64 - 1.0, image.height() as f64 - 1.0)) {
                let pxi: [u32; 2] = [px.x.round() as u32, px.y.round() as u32];

                px += direction;

                if intvl.get_last_position() == Some(&pxi) { continue; }
                intvl.push(pxi, *image.get_pixel(pxi[0], pxi[1]));
            }
            
            intervals.push(intvl);
            self.print_progress(intervals.len(), Some(start_pixels.len()));
        }

        intervals
    }
}




// ┌─────────────────────────────────────────────────────────────────────────────┐
// │                                 Radial Path                                 │
// └─────────────────────────────────────────────────────────────────────────────┘

pub(crate) struct RadialPath {
    x_offset: u32,
    y_offset: u32,
}

impl RadialPath {
    pub(crate) fn new(x_offset: u32, y_offset: u32) -> Self {
        Self { x_offset, y_offset }
    }
}

impl Path for RadialPath {
    // ┌                                                                             ┐
    // │ Intervals are generated by starting at the center of the image (+ offset)   │
    // │ and moving toward the selected pixel on the edge/border of the image until  │
    // │ the ray goes out of bounds.                                                 │
    // └                                                                             ┘
    fn get_intervals(&self, image: &ImageBuffer<Rgb<u8>, Vec<u8>>, _angle: f64) -> Vec<Interval> {
        let mut intervals: Vec<Interval> = Vec::new();
        let edge_pixels = self.get_edge_pixels(image.width(), image.height(), None);
        let image_center = Vec2::new(
            (image.width() / 2 - self.x_offset) as f64,
            (image.height() / 2 - self.y_offset) as f64
        );

        for edge_px in &edge_pixels {
            let mut intvl = Interval::new_empty();
            let mut px = Vec2::new(image_center.x, image_center.y);
            let edge_pxv = Vec2::new(edge_px[0] as f64, edge_px[1] as f64);
            let dir = image_center.direction_to(edge_pxv);

            while px.distance_to_squared(edge_pxv) > 1.0 {
                let pxi: [u32; 2] = [px.x.round() as u32, px.y.round() as u32];

                px += dir;

                if intvl.get_last_position() == Some(&pxi) { continue; }
                intvl.push(pxi, *image.get_pixel(pxi[0], pxi[1]));
            }

            intervals.push(intvl);
            self.print_progress(intervals.len(), Some(edge_pixels.len()));
        }

        intervals
    }
}


/*

"Block Sorting"" could be cool

> > > > V V V V
> > > > V V V V
> > > > V V V V
> > > > V V V V
^ ^ ^ ^ < < < <
^ ^ ^ ^ < < < <
^ ^ ^ ^ < < < <
^ ^ ^ ^ < < < <

*/

// ┌─────────────────────────────────────────────────────────────────────────────┐
// │                                 Block Path                                  │
// └─────────────────────────────────────────────────────────────────────────────┘

pub(crate) struct BlockPath {
    x_size: u32,
    y_size: u32
}

impl BlockPath {
    pub(crate) fn new(x_size: u32, y_size: u32) -> Self {
        Self { x_size, y_size }
    }
}

impl Path for BlockPath {
// ┌                                                                             ┐
// │ Intervals are generated by breaking the image into blocks (x_size, y_size)  │
// │ then deciding which direction/axis to sort in based on whether the block's  │
// │ X or Y coordinate is odd/even.                                              │
// │                                                                             │
// │ > > > > V V V V > > > > V V V V > > > > V V V V > > > > V V V V             │
// │ > > > > V V V V > > > > V V V V > > > > V V V V > > > > V V V V             │
// │ > > > > V V V V > > > > V V V V > > > > V V V V > > > > V V V V             │
// │ > > > > V V V V > > > > V V V V > > > > V V V V > > > > V V V V             │
// │ ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < <             │
// │ ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < <             │
// │ ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < <             │
// │ ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < < ^ ^ ^ ^ < < < <             │
// └                                                                             ┘
    // TODO: Making this affected by angle would be really cool
    fn get_intervals(&self, image: &ImageBuffer<Rgb<u8>, Vec<u8>>, _angle: f64) -> Vec<Interval> {
        let mut intervals: Vec<Interval> = Vec::new();

        // Get number of blocks needed to cover the screen
        let block_count: [u32; 2] = [
            (image.width() as f32 / self.x_size as f32).ceil() as u32,
            (image.height() as f32 / self.y_size as f32).ceil() as u32,
        ];

        // Block
        for bx in 0..=block_count[0] {
            for by in 0..=block_count[1] {
                let offset = [bx * self.x_size, by * self.y_size];
                let bx_even = bx.is_multiple_of(2);
                let by_even = by.is_multiple_of(2);

                let flip_x = bx_even && by_even;
                let flip_y = !bx_even && by_even;
                // True when bx_even XOR by_even.
                let outer_is_x = bx_even ^ by_even;

                let x_range: Vec<u32> = (0..=self.x_size).collect();
                let y_range: Vec<u32> = (0..=self.y_size).collect();

                let get_x = |x: u32| offset[0] + if flip_x { self.x_size - x } else { x };
                let get_y = |y: u32| offset[1] + if flip_y { self.y_size - y } else { y };

                let (outer, inner) = if outer_is_x {
                    (&x_range, &y_range)
                } else {
                    (&y_range, &x_range)
                };

                for &o in outer {
                    let mut intvl = Interval::new_empty();
                    for &i in inner {
                        let pxi = if outer_is_x {
                            [get_x(o), get_y(i)]
                        } else {
                            [get_x(i), get_y(o)]
                        };
                        if pxi[0] < image.width() && pxi[1] < image.height() {
                            intvl.push(pxi, *image.get_pixel(pxi[0], pxi[1]));
                        }
                    }
                    intervals.push(intvl);
                }
            }
        }

        intervals
    }
}
